# Generated by Django 4.2.6 on 2024-02-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebusiness',
            name='Period',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeebusiness',
            name='Series_title_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeebusiness',
            name='Suppressed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
