# Generated by Django 4.2.6 on 2024-02-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employeebusiness_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebusiness',
            name='Data_value',
            field=models.CharField(max_length=100),
        ),
    ]
